# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Object-Attribute-Cached
version:      1.00
version_from: lib/Object/Attribute/Cached.pm
installdirs:  site
requires:
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
